/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VictoriakasumuRouteImport } from './routes/victoriakasumu'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeanparkRouteImport } from './routes/seanpark'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as MunawarahmedRouteImport } from './routes/munawarahmed'
import { Route as MemberdashboardRouteImport } from './routes/memberdashboard'
import { Route as MeetveepRouteImport } from './routes/meetveep'
import { Route as MarknewhouseRouteImport } from './routes/marknewhouse'
import { Route as LauramerlingRouteImport } from './routes/lauramerling'
import { Route as JoinRouteImport } from './routes/join'
import { Route as JianyangRouteImport } from './routes/jianyang'
import { Route as JenniferkasperRouteImport } from './routes/jenniferkasper'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForPortfoliosRouteImport } from './routes/for-portfolios'
import { Route as ForCompaniesRouteImport } from './routes/for-companies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ErikavelazquezRouteImport } from './routes/erikavelazquez'
import { Route as ElainebogartRouteImport } from './routes/elainebogart'
import { Route as DavegarciaRouteImport } from './routes/davegarcia'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AndrewsilverRouteImport } from './routes/andrewsilver'
import { Route as AlasdairlloydjonesRouteImport } from './routes/alasdairlloydjones'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesInterimRouteImport } from './routes/services.interim'
import { Route as ServicesFractionalCfoRouteImport } from './routes/services.fractional-cfo'
import { Route as ServicesExecutiveBenchRouteImport } from './routes/services.executive-bench'
import { Route as ServicesAiOperatorsRouteImport } from './routes/services.ai-operators'
import { Route as CompareVsExecutiveSearchRouteImport } from './routes/compare.vs-executive-search'
import { Route as CompareVsConsultantsRouteImport } from './routes/compare.vs-consultants'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalOperatorIndexRouteImport } from './routes/_authenticated/portal/operator/index'
import { Route as AuthenticatedPortalClientIndexRouteImport } from './routes/_authenticated/portal/client/index'
import { Route as AuthenticatedPortalOperatorSupportRouteImport } from './routes/_authenticated/portal/operator/support'
import { Route as AuthenticatedPortalOperatorProfileRouteImport } from './routes/_authenticated/portal/operator/profile'
import { Route as AuthenticatedPortalOperatorPaymentsRouteImport } from './routes/_authenticated/portal/operator/payments'
import { Route as AuthenticatedPortalOperatorInvitationsRouteImport } from './routes/_authenticated/portal/operator/invitations'
import { Route as AuthenticatedPortalOperatorAvailabilityRouteImport } from './routes/_authenticated/portal/operator/availability'
import { Route as AuthenticatedPortalOperatorAssignmentsRouteImport } from './routes/_authenticated/portal/operator/assignments'
import { Route as AuthenticatedPortalOperatorAgreementsRouteImport } from './routes/_authenticated/portal/operator/agreements'
import { Route as AuthenticatedPortalClientTeamRouteImport } from './routes/_authenticated/portal/client/team'
import { Route as AuthenticatedPortalClientSupportRouteImport } from './routes/_authenticated/portal/client/support'
import { Route as AuthenticatedPortalClientProposalsRouteImport } from './routes/_authenticated/portal/client/proposals'
import { Route as AuthenticatedPortalClientJobsRouteImport } from './routes/_authenticated/portal/client/jobs'
import { Route as AuthenticatedPortalClientEngagementsRouteImport } from './routes/_authenticated/portal/client/engagements'
import { Route as AuthenticatedPortalClientDocumentsRouteImport } from './routes/_authenticated/portal/client/documents'
import { Route as AuthenticatedPortalClientBillingRouteImport } from './routes/_authenticated/portal/client/billing'

const VictoriakasumuRoute = VictoriakasumuRouteImport.update({
  id: '/victoriakasumu',
  path: '/victoriakasumu',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeanparkRoute = SeanparkRouteImport.update({
  id: '/seanpark',
  path: '/seanpark',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const MunawarahmedRoute = MunawarahmedRouteImport.update({
  id: '/munawarahmed',
  path: '/munawarahmed',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberdashboardRoute = MemberdashboardRouteImport.update({
  id: '/memberdashboard',
  path: '/memberdashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetveepRoute = MeetveepRouteImport.update({
  id: '/meetveep',
  path: '/meetveep',
  getParentRoute: () => rootRouteImport,
} as any)
const MarknewhouseRoute = MarknewhouseRouteImport.update({
  id: '/marknewhouse',
  path: '/marknewhouse',
  getParentRoute: () => rootRouteImport,
} as any)
const LauramerlingRoute = LauramerlingRouteImport.update({
  id: '/lauramerling',
  path: '/lauramerling',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const JianyangRoute = JianyangRouteImport.update({
  id: '/jianyang',
  path: '/jianyang',
  getParentRoute: () => rootRouteImport,
} as any)
const JenniferkasperRoute = JenniferkasperRouteImport.update({
  id: '/jenniferkasper',
  path: '/jenniferkasper',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPortfoliosRoute = ForPortfoliosRouteImport.update({
  id: '/for-portfolios',
  path: '/for-portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCompaniesRoute = ForCompaniesRouteImport.update({
  id: '/for-companies',
  path: '/for-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ErikavelazquezRoute = ErikavelazquezRouteImport.update({
  id: '/erikavelazquez',
  path: '/erikavelazquez',
  getParentRoute: () => rootRouteImport,
} as any)
const ElainebogartRoute = ElainebogartRouteImport.update({
  id: '/elainebogart',
  path: '/elainebogart',
  getParentRoute: () => rootRouteImport,
} as any)
const DavegarciaRoute = DavegarciaRouteImport.update({
  id: '/davegarcia',
  path: '/davegarcia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AndrewsilverRoute = AndrewsilverRouteImport.update({
  id: '/andrewsilver',
  path: '/andrewsilver',
  getParentRoute: () => rootRouteImport,
} as any)
const AlasdairlloydjonesRoute = AlasdairlloydjonesRouteImport.update({
  id: '/alasdairlloydjones',
  path: '/alasdairlloydjones',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInterimRoute = ServicesInterimRouteImport.update({
  id: '/interim',
  path: '/interim',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFractionalCfoRoute = ServicesFractionalCfoRouteImport.update({
  id: '/fractional-cfo',
  path: '/fractional-cfo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesExecutiveBenchRoute = ServicesExecutiveBenchRouteImport.update({
  id: '/executive-bench',
  path: '/executive-bench',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiOperatorsRoute = ServicesAiOperatorsRouteImport.update({
  id: '/ai-operators',
  path: '/ai-operators',
  getParentRoute: () => ServicesRoute,
} as any)
const CompareVsExecutiveSearchRoute =
  CompareVsExecutiveSearchRouteImport.update({
    id: '/vs-executive-search',
    path: '/vs-executive-search',
    getParentRoute: () => CompareRoute,
  } as any)
const CompareVsConsultantsRoute = CompareVsConsultantsRouteImport.update({
  id: '/vs-consultants',
  path: '/vs-consultants',
  getParentRoute: () => CompareRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalOperatorIndexRoute =
  AuthenticatedPortalOperatorIndexRouteImport.update({
    id: '/operator/',
    path: '/operator/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClientIndexRoute =
  AuthenticatedPortalClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalOperatorSupportRoute =
  AuthenticatedPortalOperatorSupportRouteImport.update({
    id: '/operator/support',
    path: '/operator/support',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalOperatorProfileRoute =
  AuthenticatedPortalOperatorProfileRouteImport.update({
    id: '/operator/profile',
    path: '/operator/profile',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalOperatorPaymentsRoute =
  AuthenticatedPortalOperatorPaymentsRouteImport.update({
    id: '/operator/payments',
    path: '/operator/payments',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalOperatorInvitationsRoute =
  AuthenticatedPortalOperatorInvitationsRouteImport.update({
    id: '/operator/invitations',
    path: '/operator/invitations',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalOperatorAvailabilityRoute =
  AuthenticatedPortalOperatorAvailabilityRouteImport.update({
    id: '/operator/availability',
    path: '/operator/availability',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalOperatorAssignmentsRoute =
  AuthenticatedPortalOperatorAssignmentsRouteImport.update({
    id: '/operator/assignments',
    path: '/operator/assignments',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalOperatorAgreementsRoute =
  AuthenticatedPortalOperatorAgreementsRouteImport.update({
    id: '/operator/agreements',
    path: '/operator/agreements',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClientTeamRoute =
  AuthenticatedPortalClientTeamRouteImport.update({
    id: '/client/team',
    path: '/client/team',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClientSupportRoute =
  AuthenticatedPortalClientSupportRouteImport.update({
    id: '/client/support',
    path: '/client/support',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClientProposalsRoute =
  AuthenticatedPortalClientProposalsRouteImport.update({
    id: '/client/proposals',
    path: '/client/proposals',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClientJobsRoute =
  AuthenticatedPortalClientJobsRouteImport.update({
    id: '/client/jobs',
    path: '/client/jobs',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClientEngagementsRoute =
  AuthenticatedPortalClientEngagementsRouteImport.update({
    id: '/client/engagements',
    path: '/client/engagements',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClientDocumentsRoute =
  AuthenticatedPortalClientDocumentsRouteImport.update({
    id: '/client/documents',
    path: '/client/documents',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalClientBillingRoute =
  AuthenticatedPortalClientBillingRouteImport.update({
    id: '/client/billing',
    path: '/client/billing',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alasdairlloydjones': typeof AlasdairlloydjonesRoute
  '/andrewsilver': typeof AndrewsilverRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/davegarcia': typeof DavegarciaRoute
  '/elainebogart': typeof ElainebogartRoute
  '/erikavelazquez': typeof ErikavelazquezRoute
  '/faq': typeof FaqRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-portfolios': typeof ForPortfoliosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jenniferkasper': typeof JenniferkasperRoute
  '/jianyang': typeof JianyangRoute
  '/join': typeof JoinRoute
  '/lauramerling': typeof LauramerlingRoute
  '/marknewhouse': typeof MarknewhouseRoute
  '/meetveep': typeof MeetveepRoute
  '/memberdashboard': typeof MemberdashboardRoute
  '/munawarahmed': typeof MunawarahmedRoute
  '/operators': typeof OperatorsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/seanpark': typeof SeanparkRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/victoriakasumu': typeof VictoriakasumuRoute
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/compare/vs-consultants': typeof CompareVsConsultantsRoute
  '/compare/vs-executive-search': typeof CompareVsExecutiveSearchRoute
  '/services/ai-operators': typeof ServicesAiOperatorsRoute
  '/services/executive-bench': typeof ServicesExecutiveBenchRoute
  '/services/fractional-cfo': typeof ServicesFractionalCfoRoute
  '/services/interim': typeof ServicesInterimRoute
  '/services/': typeof ServicesIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/portal/client/billing': typeof AuthenticatedPortalClientBillingRoute
  '/portal/client/documents': typeof AuthenticatedPortalClientDocumentsRoute
  '/portal/client/engagements': typeof AuthenticatedPortalClientEngagementsRoute
  '/portal/client/jobs': typeof AuthenticatedPortalClientJobsRoute
  '/portal/client/proposals': typeof AuthenticatedPortalClientProposalsRoute
  '/portal/client/support': typeof AuthenticatedPortalClientSupportRoute
  '/portal/client/team': typeof AuthenticatedPortalClientTeamRoute
  '/portal/operator/agreements': typeof AuthenticatedPortalOperatorAgreementsRoute
  '/portal/operator/assignments': typeof AuthenticatedPortalOperatorAssignmentsRoute
  '/portal/operator/availability': typeof AuthenticatedPortalOperatorAvailabilityRoute
  '/portal/operator/invitations': typeof AuthenticatedPortalOperatorInvitationsRoute
  '/portal/operator/payments': typeof AuthenticatedPortalOperatorPaymentsRoute
  '/portal/operator/profile': typeof AuthenticatedPortalOperatorProfileRoute
  '/portal/operator/support': typeof AuthenticatedPortalOperatorSupportRoute
  '/portal/client/': typeof AuthenticatedPortalClientIndexRoute
  '/portal/operator/': typeof AuthenticatedPortalOperatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alasdairlloydjones': typeof AlasdairlloydjonesRoute
  '/andrewsilver': typeof AndrewsilverRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/davegarcia': typeof DavegarciaRoute
  '/elainebogart': typeof ElainebogartRoute
  '/erikavelazquez': typeof ErikavelazquezRoute
  '/faq': typeof FaqRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-portfolios': typeof ForPortfoliosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jenniferkasper': typeof JenniferkasperRoute
  '/jianyang': typeof JianyangRoute
  '/join': typeof JoinRoute
  '/lauramerling': typeof LauramerlingRoute
  '/marknewhouse': typeof MarknewhouseRoute
  '/meetveep': typeof MeetveepRoute
  '/memberdashboard': typeof MemberdashboardRoute
  '/munawarahmed': typeof MunawarahmedRoute
  '/operators': typeof OperatorsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/seanpark': typeof SeanparkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/victoriakasumu': typeof VictoriakasumuRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/compare/vs-consultants': typeof CompareVsConsultantsRoute
  '/compare/vs-executive-search': typeof CompareVsExecutiveSearchRoute
  '/services/ai-operators': typeof ServicesAiOperatorsRoute
  '/services/executive-bench': typeof ServicesExecutiveBenchRoute
  '/services/fractional-cfo': typeof ServicesFractionalCfoRoute
  '/services/interim': typeof ServicesInterimRoute
  '/services': typeof ServicesIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/portal/client/billing': typeof AuthenticatedPortalClientBillingRoute
  '/portal/client/documents': typeof AuthenticatedPortalClientDocumentsRoute
  '/portal/client/engagements': typeof AuthenticatedPortalClientEngagementsRoute
  '/portal/client/jobs': typeof AuthenticatedPortalClientJobsRoute
  '/portal/client/proposals': typeof AuthenticatedPortalClientProposalsRoute
  '/portal/client/support': typeof AuthenticatedPortalClientSupportRoute
  '/portal/client/team': typeof AuthenticatedPortalClientTeamRoute
  '/portal/operator/agreements': typeof AuthenticatedPortalOperatorAgreementsRoute
  '/portal/operator/assignments': typeof AuthenticatedPortalOperatorAssignmentsRoute
  '/portal/operator/availability': typeof AuthenticatedPortalOperatorAvailabilityRoute
  '/portal/operator/invitations': typeof AuthenticatedPortalOperatorInvitationsRoute
  '/portal/operator/payments': typeof AuthenticatedPortalOperatorPaymentsRoute
  '/portal/operator/profile': typeof AuthenticatedPortalOperatorProfileRoute
  '/portal/operator/support': typeof AuthenticatedPortalOperatorSupportRoute
  '/portal/client': typeof AuthenticatedPortalClientIndexRoute
  '/portal/operator': typeof AuthenticatedPortalOperatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/alasdairlloydjones': typeof AlasdairlloydjonesRoute
  '/andrewsilver': typeof AndrewsilverRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/davegarcia': typeof DavegarciaRoute
  '/elainebogart': typeof ElainebogartRoute
  '/erikavelazquez': typeof ErikavelazquezRoute
  '/faq': typeof FaqRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-portfolios': typeof ForPortfoliosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jenniferkasper': typeof JenniferkasperRoute
  '/jianyang': typeof JianyangRoute
  '/join': typeof JoinRoute
  '/lauramerling': typeof LauramerlingRoute
  '/marknewhouse': typeof MarknewhouseRoute
  '/meetveep': typeof MeetveepRoute
  '/memberdashboard': typeof MemberdashboardRoute
  '/munawarahmed': typeof MunawarahmedRoute
  '/operators': typeof OperatorsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/seanpark': typeof SeanparkRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/victoriakasumu': typeof VictoriakasumuRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/compare/vs-consultants': typeof CompareVsConsultantsRoute
  '/compare/vs-executive-search': typeof CompareVsExecutiveSearchRoute
  '/services/ai-operators': typeof ServicesAiOperatorsRoute
  '/services/executive-bench': typeof ServicesExecutiveBenchRoute
  '/services/fractional-cfo': typeof ServicesFractionalCfoRoute
  '/services/interim': typeof ServicesInterimRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/portal/client/billing': typeof AuthenticatedPortalClientBillingRoute
  '/_authenticated/portal/client/documents': typeof AuthenticatedPortalClientDocumentsRoute
  '/_authenticated/portal/client/engagements': typeof AuthenticatedPortalClientEngagementsRoute
  '/_authenticated/portal/client/jobs': typeof AuthenticatedPortalClientJobsRoute
  '/_authenticated/portal/client/proposals': typeof AuthenticatedPortalClientProposalsRoute
  '/_authenticated/portal/client/support': typeof AuthenticatedPortalClientSupportRoute
  '/_authenticated/portal/client/team': typeof AuthenticatedPortalClientTeamRoute
  '/_authenticated/portal/operator/agreements': typeof AuthenticatedPortalOperatorAgreementsRoute
  '/_authenticated/portal/operator/assignments': typeof AuthenticatedPortalOperatorAssignmentsRoute
  '/_authenticated/portal/operator/availability': typeof AuthenticatedPortalOperatorAvailabilityRoute
  '/_authenticated/portal/operator/invitations': typeof AuthenticatedPortalOperatorInvitationsRoute
  '/_authenticated/portal/operator/payments': typeof AuthenticatedPortalOperatorPaymentsRoute
  '/_authenticated/portal/operator/profile': typeof AuthenticatedPortalOperatorProfileRoute
  '/_authenticated/portal/operator/support': typeof AuthenticatedPortalOperatorSupportRoute
  '/_authenticated/portal/client/': typeof AuthenticatedPortalClientIndexRoute
  '/_authenticated/portal/operator/': typeof AuthenticatedPortalOperatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alasdairlloydjones'
    | '/andrewsilver'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/davegarcia'
    | '/elainebogart'
    | '/erikavelazquez'
    | '/faq'
    | '/for-companies'
    | '/for-portfolios'
    | '/how-it-works'
    | '/jenniferkasper'
    | '/jianyang'
    | '/join'
    | '/lauramerling'
    | '/marknewhouse'
    | '/meetveep'
    | '/memberdashboard'
    | '/munawarahmed'
    | '/operators'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/proof'
    | '/seanpark'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/victoriakasumu'
    | '/portal'
    | '/admin'
    | '/dashboard'
    | '/compare/vs-consultants'
    | '/compare/vs-executive-search'
    | '/services/ai-operators'
    | '/services/executive-bench'
    | '/services/fractional-cfo'
    | '/services/interim'
    | '/services/'
    | '/portal/'
    | '/portal/client/billing'
    | '/portal/client/documents'
    | '/portal/client/engagements'
    | '/portal/client/jobs'
    | '/portal/client/proposals'
    | '/portal/client/support'
    | '/portal/client/team'
    | '/portal/operator/agreements'
    | '/portal/operator/assignments'
    | '/portal/operator/availability'
    | '/portal/operator/invitations'
    | '/portal/operator/payments'
    | '/portal/operator/profile'
    | '/portal/operator/support'
    | '/portal/client/'
    | '/portal/operator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alasdairlloydjones'
    | '/andrewsilver'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/davegarcia'
    | '/elainebogart'
    | '/erikavelazquez'
    | '/faq'
    | '/for-companies'
    | '/for-portfolios'
    | '/how-it-works'
    | '/jenniferkasper'
    | '/jianyang'
    | '/join'
    | '/lauramerling'
    | '/marknewhouse'
    | '/meetveep'
    | '/memberdashboard'
    | '/munawarahmed'
    | '/operators'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/proof'
    | '/seanpark'
    | '/sitemap.xml'
    | '/terms'
    | '/victoriakasumu'
    | '/admin'
    | '/dashboard'
    | '/compare/vs-consultants'
    | '/compare/vs-executive-search'
    | '/services/ai-operators'
    | '/services/executive-bench'
    | '/services/fractional-cfo'
    | '/services/interim'
    | '/services'
    | '/portal'
    | '/portal/client/billing'
    | '/portal/client/documents'
    | '/portal/client/engagements'
    | '/portal/client/jobs'
    | '/portal/client/proposals'
    | '/portal/client/support'
    | '/portal/client/team'
    | '/portal/operator/agreements'
    | '/portal/operator/assignments'
    | '/portal/operator/availability'
    | '/portal/operator/invitations'
    | '/portal/operator/payments'
    | '/portal/operator/profile'
    | '/portal/operator/support'
    | '/portal/client'
    | '/portal/operator'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/alasdairlloydjones'
    | '/andrewsilver'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/davegarcia'
    | '/elainebogart'
    | '/erikavelazquez'
    | '/faq'
    | '/for-companies'
    | '/for-portfolios'
    | '/how-it-works'
    | '/jenniferkasper'
    | '/jianyang'
    | '/join'
    | '/lauramerling'
    | '/marknewhouse'
    | '/meetveep'
    | '/memberdashboard'
    | '/munawarahmed'
    | '/operators'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/proof'
    | '/seanpark'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/victoriakasumu'
    | '/_authenticated/portal'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/compare/vs-consultants'
    | '/compare/vs-executive-search'
    | '/services/ai-operators'
    | '/services/executive-bench'
    | '/services/fractional-cfo'
    | '/services/interim'
    | '/services/'
    | '/_authenticated/portal/'
    | '/_authenticated/portal/client/billing'
    | '/_authenticated/portal/client/documents'
    | '/_authenticated/portal/client/engagements'
    | '/_authenticated/portal/client/jobs'
    | '/_authenticated/portal/client/proposals'
    | '/_authenticated/portal/client/support'
    | '/_authenticated/portal/client/team'
    | '/_authenticated/portal/operator/agreements'
    | '/_authenticated/portal/operator/assignments'
    | '/_authenticated/portal/operator/availability'
    | '/_authenticated/portal/operator/invitations'
    | '/_authenticated/portal/operator/payments'
    | '/_authenticated/portal/operator/profile'
    | '/_authenticated/portal/operator/support'
    | '/_authenticated/portal/client/'
    | '/_authenticated/portal/operator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlasdairlloydjonesRoute: typeof AlasdairlloydjonesRoute
  AndrewsilverRoute: typeof AndrewsilverRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRouteWithChildren
  ContactRoute: typeof ContactRoute
  DavegarciaRoute: typeof DavegarciaRoute
  ElainebogartRoute: typeof ElainebogartRoute
  ErikavelazquezRoute: typeof ErikavelazquezRoute
  FaqRoute: typeof FaqRoute
  ForCompaniesRoute: typeof ForCompaniesRoute
  ForPortfoliosRoute: typeof ForPortfoliosRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JenniferkasperRoute: typeof JenniferkasperRoute
  JianyangRoute: typeof JianyangRoute
  JoinRoute: typeof JoinRoute
  LauramerlingRoute: typeof LauramerlingRoute
  MarknewhouseRoute: typeof MarknewhouseRoute
  MeetveepRoute: typeof MeetveepRoute
  MemberdashboardRoute: typeof MemberdashboardRoute
  MunawarahmedRoute: typeof MunawarahmedRoute
  OperatorsRoute: typeof OperatorsRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProofRoute: typeof ProofRoute
  SeanparkRoute: typeof SeanparkRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VictoriakasumuRoute: typeof VictoriakasumuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/victoriakasumu': {
      id: '/victoriakasumu'
      path: '/victoriakasumu'
      fullPath: '/victoriakasumu'
      preLoaderRoute: typeof VictoriakasumuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seanpark': {
      id: '/seanpark'
      path: '/seanpark'
      fullPath: '/seanpark'
      preLoaderRoute: typeof SeanparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/munawarahmed': {
      id: '/munawarahmed'
      path: '/munawarahmed'
      fullPath: '/munawarahmed'
      preLoaderRoute: typeof MunawarahmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberdashboard': {
      id: '/memberdashboard'
      path: '/memberdashboard'
      fullPath: '/memberdashboard'
      preLoaderRoute: typeof MemberdashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetveep': {
      id: '/meetveep'
      path: '/meetveep'
      fullPath: '/meetveep'
      preLoaderRoute: typeof MeetveepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marknewhouse': {
      id: '/marknewhouse'
      path: '/marknewhouse'
      fullPath: '/marknewhouse'
      preLoaderRoute: typeof MarknewhouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lauramerling': {
      id: '/lauramerling'
      path: '/lauramerling'
      fullPath: '/lauramerling'
      preLoaderRoute: typeof LauramerlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jianyang': {
      id: '/jianyang'
      path: '/jianyang'
      fullPath: '/jianyang'
      preLoaderRoute: typeof JianyangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jenniferkasper': {
      id: '/jenniferkasper'
      path: '/jenniferkasper'
      fullPath: '/jenniferkasper'
      preLoaderRoute: typeof JenniferkasperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-portfolios': {
      id: '/for-portfolios'
      path: '/for-portfolios'
      fullPath: '/for-portfolios'
      preLoaderRoute: typeof ForPortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-companies': {
      id: '/for-companies'
      path: '/for-companies'
      fullPath: '/for-companies'
      preLoaderRoute: typeof ForCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erikavelazquez': {
      id: '/erikavelazquez'
      path: '/erikavelazquez'
      fullPath: '/erikavelazquez'
      preLoaderRoute: typeof ErikavelazquezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elainebogart': {
      id: '/elainebogart'
      path: '/elainebogart'
      fullPath: '/elainebogart'
      preLoaderRoute: typeof ElainebogartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davegarcia': {
      id: '/davegarcia'
      path: '/davegarcia'
      fullPath: '/davegarcia'
      preLoaderRoute: typeof DavegarciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/andrewsilver': {
      id: '/andrewsilver'
      path: '/andrewsilver'
      fullPath: '/andrewsilver'
      preLoaderRoute: typeof AndrewsilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alasdairlloydjones': {
      id: '/alasdairlloydjones'
      path: '/alasdairlloydjones'
      fullPath: '/alasdairlloydjones'
      preLoaderRoute: typeof AlasdairlloydjonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/interim': {
      id: '/services/interim'
      path: '/interim'
      fullPath: '/services/interim'
      preLoaderRoute: typeof ServicesInterimRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/fractional-cfo': {
      id: '/services/fractional-cfo'
      path: '/fractional-cfo'
      fullPath: '/services/fractional-cfo'
      preLoaderRoute: typeof ServicesFractionalCfoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/executive-bench': {
      id: '/services/executive-bench'
      path: '/executive-bench'
      fullPath: '/services/executive-bench'
      preLoaderRoute: typeof ServicesExecutiveBenchRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-operators': {
      id: '/services/ai-operators'
      path: '/ai-operators'
      fullPath: '/services/ai-operators'
      preLoaderRoute: typeof ServicesAiOperatorsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/compare/vs-executive-search': {
      id: '/compare/vs-executive-search'
      path: '/vs-executive-search'
      fullPath: '/compare/vs-executive-search'
      preLoaderRoute: typeof CompareVsExecutiveSearchRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/vs-consultants': {
      id: '/compare/vs-consultants'
      path: '/vs-consultants'
      fullPath: '/compare/vs-consultants'
      preLoaderRoute: typeof CompareVsConsultantsRouteImport
      parentRoute: typeof CompareRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/operator/': {
      id: '/_authenticated/portal/operator/'
      path: '/operator'
      fullPath: '/portal/operator/'
      preLoaderRoute: typeof AuthenticatedPortalOperatorIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/client/': {
      id: '/_authenticated/portal/client/'
      path: '/client'
      fullPath: '/portal/client/'
      preLoaderRoute: typeof AuthenticatedPortalClientIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/operator/support': {
      id: '/_authenticated/portal/operator/support'
      path: '/operator/support'
      fullPath: '/portal/operator/support'
      preLoaderRoute: typeof AuthenticatedPortalOperatorSupportRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/operator/profile': {
      id: '/_authenticated/portal/operator/profile'
      path: '/operator/profile'
      fullPath: '/portal/operator/profile'
      preLoaderRoute: typeof AuthenticatedPortalOperatorProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/operator/payments': {
      id: '/_authenticated/portal/operator/payments'
      path: '/operator/payments'
      fullPath: '/portal/operator/payments'
      preLoaderRoute: typeof AuthenticatedPortalOperatorPaymentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/operator/invitations': {
      id: '/_authenticated/portal/operator/invitations'
      path: '/operator/invitations'
      fullPath: '/portal/operator/invitations'
      preLoaderRoute: typeof AuthenticatedPortalOperatorInvitationsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/operator/availability': {
      id: '/_authenticated/portal/operator/availability'
      path: '/operator/availability'
      fullPath: '/portal/operator/availability'
      preLoaderRoute: typeof AuthenticatedPortalOperatorAvailabilityRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/operator/assignments': {
      id: '/_authenticated/portal/operator/assignments'
      path: '/operator/assignments'
      fullPath: '/portal/operator/assignments'
      preLoaderRoute: typeof AuthenticatedPortalOperatorAssignmentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/operator/agreements': {
      id: '/_authenticated/portal/operator/agreements'
      path: '/operator/agreements'
      fullPath: '/portal/operator/agreements'
      preLoaderRoute: typeof AuthenticatedPortalOperatorAgreementsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/client/team': {
      id: '/_authenticated/portal/client/team'
      path: '/client/team'
      fullPath: '/portal/client/team'
      preLoaderRoute: typeof AuthenticatedPortalClientTeamRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/client/support': {
      id: '/_authenticated/portal/client/support'
      path: '/client/support'
      fullPath: '/portal/client/support'
      preLoaderRoute: typeof AuthenticatedPortalClientSupportRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/client/proposals': {
      id: '/_authenticated/portal/client/proposals'
      path: '/client/proposals'
      fullPath: '/portal/client/proposals'
      preLoaderRoute: typeof AuthenticatedPortalClientProposalsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/client/jobs': {
      id: '/_authenticated/portal/client/jobs'
      path: '/client/jobs'
      fullPath: '/portal/client/jobs'
      preLoaderRoute: typeof AuthenticatedPortalClientJobsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/client/engagements': {
      id: '/_authenticated/portal/client/engagements'
      path: '/client/engagements'
      fullPath: '/portal/client/engagements'
      preLoaderRoute: typeof AuthenticatedPortalClientEngagementsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/client/documents': {
      id: '/_authenticated/portal/client/documents'
      path: '/client/documents'
      fullPath: '/portal/client/documents'
      preLoaderRoute: typeof AuthenticatedPortalClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/client/billing': {
      id: '/_authenticated/portal/client/billing'
      path: '/client/billing'
      fullPath: '/portal/client/billing'
      preLoaderRoute: typeof AuthenticatedPortalClientBillingRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
  }
}

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalClientBillingRoute: typeof AuthenticatedPortalClientBillingRoute
  AuthenticatedPortalClientDocumentsRoute: typeof AuthenticatedPortalClientDocumentsRoute
  AuthenticatedPortalClientEngagementsRoute: typeof AuthenticatedPortalClientEngagementsRoute
  AuthenticatedPortalClientJobsRoute: typeof AuthenticatedPortalClientJobsRoute
  AuthenticatedPortalClientProposalsRoute: typeof AuthenticatedPortalClientProposalsRoute
  AuthenticatedPortalClientSupportRoute: typeof AuthenticatedPortalClientSupportRoute
  AuthenticatedPortalClientTeamRoute: typeof AuthenticatedPortalClientTeamRoute
  AuthenticatedPortalOperatorAgreementsRoute: typeof AuthenticatedPortalOperatorAgreementsRoute
  AuthenticatedPortalOperatorAssignmentsRoute: typeof AuthenticatedPortalOperatorAssignmentsRoute
  AuthenticatedPortalOperatorAvailabilityRoute: typeof AuthenticatedPortalOperatorAvailabilityRoute
  AuthenticatedPortalOperatorInvitationsRoute: typeof AuthenticatedPortalOperatorInvitationsRoute
  AuthenticatedPortalOperatorPaymentsRoute: typeof AuthenticatedPortalOperatorPaymentsRoute
  AuthenticatedPortalOperatorProfileRoute: typeof AuthenticatedPortalOperatorProfileRoute
  AuthenticatedPortalOperatorSupportRoute: typeof AuthenticatedPortalOperatorSupportRoute
  AuthenticatedPortalClientIndexRoute: typeof AuthenticatedPortalClientIndexRoute
  AuthenticatedPortalOperatorIndexRoute: typeof AuthenticatedPortalOperatorIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
    AuthenticatedPortalClientBillingRoute:
      AuthenticatedPortalClientBillingRoute,
    AuthenticatedPortalClientDocumentsRoute:
      AuthenticatedPortalClientDocumentsRoute,
    AuthenticatedPortalClientEngagementsRoute:
      AuthenticatedPortalClientEngagementsRoute,
    AuthenticatedPortalClientJobsRoute: AuthenticatedPortalClientJobsRoute,
    AuthenticatedPortalClientProposalsRoute:
      AuthenticatedPortalClientProposalsRoute,
    AuthenticatedPortalClientSupportRoute:
      AuthenticatedPortalClientSupportRoute,
    AuthenticatedPortalClientTeamRoute: AuthenticatedPortalClientTeamRoute,
    AuthenticatedPortalOperatorAgreementsRoute:
      AuthenticatedPortalOperatorAgreementsRoute,
    AuthenticatedPortalOperatorAssignmentsRoute:
      AuthenticatedPortalOperatorAssignmentsRoute,
    AuthenticatedPortalOperatorAvailabilityRoute:
      AuthenticatedPortalOperatorAvailabilityRoute,
    AuthenticatedPortalOperatorInvitationsRoute:
      AuthenticatedPortalOperatorInvitationsRoute,
    AuthenticatedPortalOperatorPaymentsRoute:
      AuthenticatedPortalOperatorPaymentsRoute,
    AuthenticatedPortalOperatorProfileRoute:
      AuthenticatedPortalOperatorProfileRoute,
    AuthenticatedPortalOperatorSupportRoute:
      AuthenticatedPortalOperatorSupportRoute,
    AuthenticatedPortalClientIndexRoute: AuthenticatedPortalClientIndexRoute,
    AuthenticatedPortalOperatorIndexRoute:
      AuthenticatedPortalOperatorIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CompareRouteChildren {
  CompareVsConsultantsRoute: typeof CompareVsConsultantsRoute
  CompareVsExecutiveSearchRoute: typeof CompareVsExecutiveSearchRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareVsConsultantsRoute: CompareVsConsultantsRoute,
  CompareVsExecutiveSearchRoute: CompareVsExecutiveSearchRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

interface ServicesRouteChildren {
  ServicesAiOperatorsRoute: typeof ServicesAiOperatorsRoute
  ServicesExecutiveBenchRoute: typeof ServicesExecutiveBenchRoute
  ServicesFractionalCfoRoute: typeof ServicesFractionalCfoRoute
  ServicesInterimRoute: typeof ServicesInterimRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiOperatorsRoute: ServicesAiOperatorsRoute,
  ServicesExecutiveBenchRoute: ServicesExecutiveBenchRoute,
  ServicesFractionalCfoRoute: ServicesFractionalCfoRoute,
  ServicesInterimRoute: ServicesInterimRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AlasdairlloydjonesRoute: AlasdairlloydjonesRoute,
  AndrewsilverRoute: AndrewsilverRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRouteWithChildren,
  ContactRoute: ContactRoute,
  DavegarciaRoute: DavegarciaRoute,
  ElainebogartRoute: ElainebogartRoute,
  ErikavelazquezRoute: ErikavelazquezRoute,
  FaqRoute: FaqRoute,
  ForCompaniesRoute: ForCompaniesRoute,
  ForPortfoliosRoute: ForPortfoliosRoute,
  HowItWorksRoute: HowItWorksRoute,
  JenniferkasperRoute: JenniferkasperRoute,
  JianyangRoute: JianyangRoute,
  JoinRoute: JoinRoute,
  LauramerlingRoute: LauramerlingRoute,
  MarknewhouseRoute: MarknewhouseRoute,
  MeetveepRoute: MeetveepRoute,
  MemberdashboardRoute: MemberdashboardRoute,
  MunawarahmedRoute: MunawarahmedRoute,
  OperatorsRoute: OperatorsRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProofRoute: ProofRoute,
  SeanparkRoute: SeanparkRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VictoriakasumuRoute: VictoriakasumuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
