/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForPortfoliosRouteImport } from './routes/for-portfolios'
import { Route as ForCompaniesRouteImport } from './routes/for-companies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesInterimRouteImport } from './routes/services.interim'
import { Route as ServicesFractionalCfoRouteImport } from './routes/services.fractional-cfo'
import { Route as ServicesExecutiveBenchRouteImport } from './routes/services.executive-bench'
import { Route as ServicesAiOperatorsRouteImport } from './routes/services.ai-operators'
import { Route as CompareVsExecutiveSearchRouteImport } from './routes/compare.vs-executive-search'
import { Route as CompareVsConsultantsRouteImport } from './routes/compare.vs-consultants'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPortfoliosRoute = ForPortfoliosRouteImport.update({
  id: '/for-portfolios',
  path: '/for-portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCompaniesRoute = ForCompaniesRouteImport.update({
  id: '/for-companies',
  path: '/for-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInterimRoute = ServicesInterimRouteImport.update({
  id: '/interim',
  path: '/interim',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFractionalCfoRoute = ServicesFractionalCfoRouteImport.update({
  id: '/fractional-cfo',
  path: '/fractional-cfo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesExecutiveBenchRoute = ServicesExecutiveBenchRouteImport.update({
  id: '/executive-bench',
  path: '/executive-bench',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiOperatorsRoute = ServicesAiOperatorsRouteImport.update({
  id: '/ai-operators',
  path: '/ai-operators',
  getParentRoute: () => ServicesRoute,
} as any)
const CompareVsExecutiveSearchRoute =
  CompareVsExecutiveSearchRouteImport.update({
    id: '/vs-executive-search',
    path: '/vs-executive-search',
    getParentRoute: () => CompareRoute,
  } as any)
const CompareVsConsultantsRoute = CompareVsConsultantsRouteImport.update({
  id: '/vs-consultants',
  path: '/vs-consultants',
  getParentRoute: () => CompareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-portfolios': typeof ForPortfoliosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/join': typeof JoinRoute
  '/operators': typeof OperatorsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/compare/vs-consultants': typeof CompareVsConsultantsRoute
  '/compare/vs-executive-search': typeof CompareVsExecutiveSearchRoute
  '/services/ai-operators': typeof ServicesAiOperatorsRoute
  '/services/executive-bench': typeof ServicesExecutiveBenchRoute
  '/services/fractional-cfo': typeof ServicesFractionalCfoRoute
  '/services/interim': typeof ServicesInterimRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-portfolios': typeof ForPortfoliosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/join': typeof JoinRoute
  '/operators': typeof OperatorsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/compare/vs-consultants': typeof CompareVsConsultantsRoute
  '/compare/vs-executive-search': typeof CompareVsExecutiveSearchRoute
  '/services/ai-operators': typeof ServicesAiOperatorsRoute
  '/services/executive-bench': typeof ServicesExecutiveBenchRoute
  '/services/fractional-cfo': typeof ServicesFractionalCfoRoute
  '/services/interim': typeof ServicesInterimRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-portfolios': typeof ForPortfoliosRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insights': typeof InsightsRoute
  '/join': typeof JoinRoute
  '/operators': typeof OperatorsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/compare/vs-consultants': typeof CompareVsConsultantsRoute
  '/compare/vs-executive-search': typeof CompareVsExecutiveSearchRoute
  '/services/ai-operators': typeof ServicesAiOperatorsRoute
  '/services/executive-bench': typeof ServicesExecutiveBenchRoute
  '/services/fractional-cfo': typeof ServicesFractionalCfoRoute
  '/services/interim': typeof ServicesInterimRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/for-companies'
    | '/for-portfolios'
    | '/how-it-works'
    | '/insights'
    | '/join'
    | '/operators'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/proof'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/compare/vs-consultants'
    | '/compare/vs-executive-search'
    | '/services/ai-operators'
    | '/services/executive-bench'
    | '/services/fractional-cfo'
    | '/services/interim'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/for-companies'
    | '/for-portfolios'
    | '/how-it-works'
    | '/insights'
    | '/join'
    | '/operators'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/proof'
    | '/sitemap.xml'
    | '/terms'
    | '/compare/vs-consultants'
    | '/compare/vs-executive-search'
    | '/services/ai-operators'
    | '/services/executive-bench'
    | '/services/fractional-cfo'
    | '/services/interim'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/for-companies'
    | '/for-portfolios'
    | '/how-it-works'
    | '/insights'
    | '/join'
    | '/operators'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/proof'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/compare/vs-consultants'
    | '/compare/vs-executive-search'
    | '/services/ai-operators'
    | '/services/executive-bench'
    | '/services/fractional-cfo'
    | '/services/interim'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompareRoute: typeof CompareRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForCompaniesRoute: typeof ForCompaniesRoute
  ForPortfoliosRoute: typeof ForPortfoliosRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InsightsRoute: typeof InsightsRoute
  JoinRoute: typeof JoinRoute
  OperatorsRoute: typeof OperatorsRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProofRoute: typeof ProofRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-portfolios': {
      id: '/for-portfolios'
      path: '/for-portfolios'
      fullPath: '/for-portfolios'
      preLoaderRoute: typeof ForPortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-companies': {
      id: '/for-companies'
      path: '/for-companies'
      fullPath: '/for-companies'
      preLoaderRoute: typeof ForCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/interim': {
      id: '/services/interim'
      path: '/interim'
      fullPath: '/services/interim'
      preLoaderRoute: typeof ServicesInterimRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/fractional-cfo': {
      id: '/services/fractional-cfo'
      path: '/fractional-cfo'
      fullPath: '/services/fractional-cfo'
      preLoaderRoute: typeof ServicesFractionalCfoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/executive-bench': {
      id: '/services/executive-bench'
      path: '/executive-bench'
      fullPath: '/services/executive-bench'
      preLoaderRoute: typeof ServicesExecutiveBenchRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-operators': {
      id: '/services/ai-operators'
      path: '/ai-operators'
      fullPath: '/services/ai-operators'
      preLoaderRoute: typeof ServicesAiOperatorsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/compare/vs-executive-search': {
      id: '/compare/vs-executive-search'
      path: '/vs-executive-search'
      fullPath: '/compare/vs-executive-search'
      preLoaderRoute: typeof CompareVsExecutiveSearchRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/vs-consultants': {
      id: '/compare/vs-consultants'
      path: '/vs-consultants'
      fullPath: '/compare/vs-consultants'
      preLoaderRoute: typeof CompareVsConsultantsRouteImport
      parentRoute: typeof CompareRoute
    }
  }
}

interface CompareRouteChildren {
  CompareVsConsultantsRoute: typeof CompareVsConsultantsRoute
  CompareVsExecutiveSearchRoute: typeof CompareVsExecutiveSearchRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareVsConsultantsRoute: CompareVsConsultantsRoute,
  CompareVsExecutiveSearchRoute: CompareVsExecutiveSearchRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

interface ServicesRouteChildren {
  ServicesAiOperatorsRoute: typeof ServicesAiOperatorsRoute
  ServicesExecutiveBenchRoute: typeof ServicesExecutiveBenchRoute
  ServicesFractionalCfoRoute: typeof ServicesFractionalCfoRoute
  ServicesInterimRoute: typeof ServicesInterimRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiOperatorsRoute: ServicesAiOperatorsRoute,
  ServicesExecutiveBenchRoute: ServicesExecutiveBenchRoute,
  ServicesFractionalCfoRoute: ServicesFractionalCfoRoute,
  ServicesInterimRoute: ServicesInterimRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompareRoute: CompareRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForCompaniesRoute: ForCompaniesRoute,
  ForPortfoliosRoute: ForPortfoliosRoute,
  HowItWorksRoute: HowItWorksRoute,
  InsightsRoute: InsightsRoute,
  JoinRoute: JoinRoute,
  OperatorsRoute: OperatorsRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProofRoute: ProofRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
